# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: monthly
    target-branch: develop

version: 2
