jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.14.0
      - run: "deno install -qAn vr https://deno.land/x/velociraptor@1.2.0/cli.ts"
      - run: "deno run -A https://deno.land/x/aleph@v0.3.0-beta.17/install.ts"
      - run: "vr build"

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.14.0
      - run: "deno install -qAn vr https://deno.land/x/velociraptor@1.2.0/cli.ts"
      - run: "vr lint"

name: "Build And Lint"

on:
  push:
    branches-ignore:
      - main
